// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id int64) error
	GetNote(ctx context.Context, id int64) (Note, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListNotesByUserID(ctx context.Context, userID int64) ([]Note, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeSession(ctx context.Context, id string) error
	RevokeUserSessions(ctx context.Context, userID int64) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UserExists(ctx context.Context, id int64) (bool, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
