// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/meads/notes-api/internal/handler (interfaces: NoteServicer)
//
// Generated by this command:
//
//	mockgen -package handler -destination ./internal/handler/note_service_mock.go github.com/meads/notes-api/internal/handler NoteServicer
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	domain "github.com/meads/notes-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteServicer is a mock of NoteServicer interface.
type MockNoteServicer struct {
	ctrl     *gomock.Controller
	recorder *MockNoteServicerMockRecorder
	isgomock struct{}
}

// MockNoteServicerMockRecorder is the mock recorder for MockNoteServicer.
type MockNoteServicerMockRecorder struct {
	mock *MockNoteServicer
}

// NewMockNoteServicer creates a new mock instance.
func NewMockNoteServicer(ctrl *gomock.Controller) *MockNoteServicer {
	mock := &MockNoteServicer{ctrl: ctrl}
	mock.recorder = &MockNoteServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteServicer) EXPECT() *MockNoteServicerMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockNoteServicer) CreateNote(ctx context.Context, userID int64, title, content string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, userID, title, content)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteServicerMockRecorder) CreateNote(ctx, userID, title, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteServicer)(nil).CreateNote), ctx, userID, title, content)
}

// DeleteNote mocks base method.
func (m *MockNoteServicer) DeleteNote(ctx context.Context, noteID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteServicerMockRecorder) DeleteNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteServicer)(nil).DeleteNote), ctx, noteID, userID)
}

// ListNotes mocks base method.
func (m *MockNoteServicer) ListNotes(ctx context.Context, userID int64) ([]domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes", ctx, userID)
	ret0, _ := ret[0].([]domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockNoteServicerMockRecorder) ListNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockNoteServicer)(nil).ListNotes), ctx, userID)
}

// UpdateNote mocks base method.
func (m *MockNoteServicer) UpdateNote(ctx context.Context, noteID, userID int64, title, content string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, userID, title, content)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteServicerMockRecorder) UpdateNote(ctx, noteID, userID, title, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteServicer)(nil).UpdateNote), ctx, noteID, userID, title, content)
}
