// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/meads/notes-api/internal/security (interfaces: Tokener)
//
// Generated by this command:
//
//	mockgen -package security -destination ./internal/security/claims_mock.go github.com/meads/notes-api/internal/security Tokener
//

// Package security is a generated GoMock package.
package security

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokener is a mock of Tokener interface.
type MockTokener struct {
	ctrl     *gomock.Controller
	recorder *MockTokenerMockRecorder
	isgomock struct{}
}

// MockTokenerMockRecorder is the mock recorder for MockTokener.
type MockTokenerMockRecorder struct {
	mock *MockTokener
}

// NewMockTokener creates a new mock instance.
func NewMockTokener(ctrl *gomock.Controller) *MockTokener {
	mock := &MockTokener{ctrl: ctrl}
	mock.recorder = &MockTokenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokener) EXPECT() *MockTokenerMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockTokener) GenerateToken(userID int64, username, usage string, duration time.Duration) (string, *UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID, username, usage, duration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*UserClaims)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenerMockRecorder) GenerateToken(userID, username, usage, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokener)(nil).GenerateToken), userID, username, usage, duration)
}

// VerifyToken mocks base method.
func (m *MockTokener) VerifyToken(tokenString string) (*UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(*UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenerMockRecorder) VerifyToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokener)(nil).VerifyToken), tokenString)
}
